import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Together List',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const cookieStore = cookies();
  // const sessionToken = cookieStore.get('sessionToken');
  // console.log(sessionToken);
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header></Header> */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
